import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration for the Physical AI & Humanoid Robotics textbook
  tutorialSidebar: [
    // "content-maintenance-guide",
    {
      type: "category",
      label: "Introduction",
      items: ["intro"],
      collapsed: false,
    },
    {
      type: "category",
      label: "Module 1: The Robotic Nervous System (ROS 2)",
      items: [
        "module1/index",
        "module1/1-1-introduction-to-ros2",
        "module1/1-2-ros2-nodes-topics-services",
        "module1/1-3-python-agents-ros-controllers",
        "module1/1-4-understanding-urdf-humanoids",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Module 2: The Digital Twin (Gazebo & Unity)",
      items: [
        "module2/index",
        "module2/2-1-physics-simulation-gazebo",
        "module2/2-2-high-fidelity-rendering-unity",
        "module2/2-3-sensor-simulation-liar-cameras-imus",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Module 3: The AI-Robot Brain (NVIDIA Isaac)",
      items: [
        "module3/index",
        "module3/3-1-nvidia-isaac-sim-photorealistic-simulation",
        "module3/3-2-isaac-ros-vslam-navigation",
        "module3/3-3-nav2-path-planning-bipedal-humanoids",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Module 4: Vision-Language-Action (VLA)",
      items: [
        "module4/index",
        "module4/4-1-voice-action-openai-whisper",
        "module4/4-2-cognitive-planning-language-ros2-actions",
        "module4/4-3-multimodal-interaction-speech-vision-gesture",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Capstone: The Autonomous Humanoid",
      items: [
        "capstone/index",
        "capstone/5-1-project-overview",
        "capstone/5-2-voice-command-processing",
        "capstone/5-3-navigation-obstacle-handling",
        "capstone/5-4-object-recognition-manipulation",
        "capstone/5-5-final-integration-demonstration",
      ],
      collapsed: false,
    },
  ],
  // Add this to STOP Docusaurus from auto-scanning extra files
  // @ts-ignore
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [Symbol.for("disableAutogeneratedSidebar")]: true,
};

export default sidebars;
